// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService provides bindings for the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scribe$0 from "./internal/models.js";

/**
 * AcceptTerms records the user's acceptance of the terms and conditions
 * @returns {$CancellablePromise<void>}
 */
export function AcceptTerms() {
    return $Call.ByID(3427182873);
}

/**
 * AddSkillToWorkspace adds a skill to a specific workspace
 * @param {string} skillName
 * @param {string} workspaceName
 * @returns {$CancellablePromise<void>}
 */
export function AddSkillToWorkspace(skillName, workspaceName) {
    return $Call.ByID(4153998260, skillName, workspaceName);
}

/**
 * AreTermsAccepted checks if the user has accepted the terms and conditions
 * @returns {$CancellablePromise<boolean>}
 */
export function AreTermsAccepted() {
    return $Call.ByID(943679626);
}

/**
 * CancelDiscover cancels a pending discovery and cleans up resources
 * @returns {$CancellablePromise<void>}
 */
export function CancelDiscover() {
    return $Call.ByID(211984487);
}

/**
 * CheckForAppUpdate queries GitHub for the latest release and returns update info
 * @returns {$CancellablePromise<scribe$0.UpdateInfo | null>}
 */
export function CheckForAppUpdate() {
    return $Call.ByID(899838745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckSourceGroupUpdates checks all installed source groups for available updates.
 * Each remote repository is fetched only once regardless of how many skills it contains.
 * @returns {$CancellablePromise<{ [_ in string]?: scribe$0.SourceGroupCheckResult }>}
 */
export function CheckSourceGroupUpdates() {
    return $Call.ByID(2948528492).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CompleteOnboarding marks onboarding as completed
 * @returns {$CancellablePromise<void>}
 */
export function CompleteOnboarding() {
    return $Call.ByID(3633971812);
}

/**
 * ConfirmInstall installs previously discovered skills and optionally adds them to workspaces
 * @param {string[]} skillNames
 * @param {string[]} workspaceNames
 * @returns {$CancellablePromise<scribe$0.InstallResult | null>}
 */
export function ConfirmInstall(skillNames, workspaceNames) {
    return $Call.ByID(3145554929, skillNames, workspaceNames).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateWorkspace creates a new workspace
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function CreateWorkspace(name, description) {
    return $Call.ByID(771272559, name, description);
}

/**
 * DeleteAllExistingSkills removes all detected skills from agent directories
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAllExistingSkills() {
    return $Call.ByID(3918992643);
}

/**
 * DeleteWorkspace removes a workspace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorkspace(name) {
    return $Call.ByID(1487213990, name);
}

/**
 * DetectExistingSkills scans agent directories for existing skills
 * @returns {$CancellablePromise<scribe$0.ExistingSkillInfo[]>}
 */
export function DetectExistingSkills() {
    return $Call.ByID(523942446).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DetectSkillConflicts finds skills with the same name in different agent directories
 * @returns {$CancellablePromise<scribe$0.SkillConflict[]>}
 */
export function DetectSkillConflicts() {
    return $Call.ByID(2461598757).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * DiscoverFromSource fetches a source and returns discovered skills without installing
 * @param {string} sourceStr
 * @returns {$CancellablePromise<scribe$0.DiscoverResult | null>}
 */
export function DiscoverFromSource(sourceStr) {
    return $Call.ByID(3177530224, sourceStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetActiveWorkspaceName returns the name of the active workspace
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveWorkspaceName() {
    return $Call.ByID(1690274030);
}

/**
 * GetAgentStatus returns the status of all supported agents
 * @returns {$CancellablePromise<scribe$0.AgentStatus[]>}
 */
export function GetAgentStatus() {
    return $Call.ByID(2322632773).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetInstallMethod returns how Scribe was installed ("app-bundle", "binary", "dev", "unknown").
 * @returns {$CancellablePromise<string>}
 */
export function GetInstallMethod() {
    return $Call.ByID(3704321848);
}

/**
 * GetInstalledAgentCount returns how many agents are installed
 * @returns {$CancellablePromise<number>}
 */
export function GetInstalledAgentCount() {
    return $Call.ByID(4143454204);
}

/**
 * GetMarketplaceProviders returns available marketplace provider IDs and display names
 * @returns {$CancellablePromise<scribe$0.MarketplaceProviderInfo[]>}
 */
export function GetMarketplaceProviders() {
    return $Call.ByID(3456634905).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetRepoReadme fetches the README.md content for a GitHub repository
 * @param {string} owner
 * @param {string} repo
 * @returns {$CancellablePromise<string>}
 */
export function GetRepoReadme(owner, repo) {
    return $Call.ByID(3372007624, owner, repo);
}

/**
 * GetSkillAudits fetches vulnerability audit results for an AgentHub skill
 * @param {string} authorName
 * @param {string} repoSlug
 * @param {string} name
 * @returns {$CancellablePromise<scribe$0.SkillAuditResult | null>}
 */
export function GetSkillAudits(authorName, repoSlug, name) {
    return $Call.ByID(284040943, authorName, repoSlug, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetSkillContent returns the SKILL.md body content (markdown after frontmatter) for a skill
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetSkillContent(name) {
    return $Call.ByID(2591899112, name);
}

/**
 * GetSkillCount returns the number of installed skills
 * @returns {$CancellablePromise<number>}
 */
export function GetSkillCount() {
    return $Call.ByID(810176198);
}

/**
 * GetSkills returns all installed skills
 * @returns {$CancellablePromise<scribe$0.SkillInfo[]>}
 */
export function GetSkills() {
    return $Call.ByID(2802882116).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetTermsAcceptedAt returns the RFC3339 timestamp of when terms were accepted, or empty string
 * @returns {$CancellablePromise<string>}
 */
export function GetTermsAcceptedAt() {
    return $Call.ByID(1036645685);
}

/**
 * GetTermsClauses returns the terms and conditions clauses (single source of truth)
 * @returns {$CancellablePromise<scribe$0.TermsClause[]>}
 */
export function GetTermsClauses() {
    return $Call.ByID(1021629297).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetTotalAgentCount returns the total number of supported agents
 * @returns {$CancellablePromise<number>}
 */
export function GetTotalAgentCount() {
    return $Call.ByID(494676592);
}

/**
 * GetVersion returns the application version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(2729898890);
}

/**
 * GetWorkspaces returns all workspaces with their active status
 * @returns {$CancellablePromise<scribe$0.WorkspaceInfo[]>}
 */
export function GetWorkspaces() {
    return $Call.ByID(1333717852).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ImportAllExistingSkills imports all detected skills to ~/.scribe/scrolls/
 * @returns {$CancellablePromise<void>}
 */
export function ImportAllExistingSkills() {
    return $Call.ByID(3893015977);
}

/**
 * InstallDemoSkill installs the scribe-welcome demo skill
 * @returns {$CancellablePromise<void>}
 */
export function InstallDemoSkill() {
    return $Call.ByID(2768326139);
}

/**
 * InstallFromSource installs skills from a source string (e.g. "owner/repo", GitHub URL, zip URL)
 * @param {string} sourceStr
 * @returns {$CancellablePromise<scribe$0.InstallResult | null>}
 */
export function InstallFromSource(sourceStr) {
    return $Call.ByID(2602832348, sourceStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * IsOnboardingCompleted checks if onboarding has been completed
 * @returns {$CancellablePromise<boolean>}
 */
export function IsOnboardingCompleted() {
    return $Call.ByID(601702516);
}

/**
 * IsUpdateNotificationsDisabled returns whether the user has suppressed update toasts
 * @returns {$CancellablePromise<boolean>}
 */
export function IsUpdateNotificationsDisabled() {
    return $Call.ByID(563920977);
}

/**
 * Log writes a log message from the frontend to the unified log file.
 * Valid levels: "debug", "info", "warn", "error".
 * @param {string} level
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function Log(level, message) {
    return $Call.ByID(1684063072, level, message);
}

/**
 * RemoveSkill removes a skill by name from all agents and workspaces
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSkill(name) {
    return $Call.ByID(3665032119, name);
}

/**
 * RemoveSkillFromWorkspace removes a skill from a specific workspace
 * @param {string} skillName
 * @param {string} workspaceName
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSkillFromWorkspace(skillName, workspaceName) {
    return $Call.ByID(2402846048, skillName, workspaceName);
}

/**
 * ResolveSkillConflict imports a specific skill version when there's a naming conflict
 * @param {string} skillPath
 * @returns {$CancellablePromise<void>}
 */
export function ResolveSkillConflict(skillPath) {
    return $Call.ByID(391349041, skillPath);
}

/**
 * RestartApp relaunches the Scribe application and quits the current instance.
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(2950999540);
}

/**
 * ResyncWorkspace forces a resync of all skills in current workspace to agents
 * @returns {$CancellablePromise<void>}
 */
export function ResyncWorkspace() {
    return $Call.ByID(526204877);
}

/**
 * SearchMarketplace searches for skill repos using the specified provider
 * @param {string} providerID
 * @param {string} query
 * @param {number} page
 * @returns {$CancellablePromise<scribe$0.MarketplaceResult | null>}
 */
export function SearchMarketplace(providerID, query, page) {
    return $Call.ByID(1884638741, providerID, query, page).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * SetActiveWorkspace switches to a different workspace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveWorkspace(name) {
    return $Call.ByID(300915577, name);
}

/**
 * SetUpdateNotificationsDisabled sets the user's preference for update notifications
 * @param {boolean} disabled
 * @returns {$CancellablePromise<void>}
 */
export function SetUpdateNotificationsDisabled(disabled) {
    return $Call.ByID(368726301, disabled);
}

/**
 * UpdateSkill updates a skill to its latest version from the original source
 * @param {string} name
 * @returns {$CancellablePromise<scribe$0.UpdateResult | null>}
 */
export function UpdateSkill(name) {
    return $Call.ByID(3791305904, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * UpgradeApp performs a self-update of the Scribe binary.
 * @returns {$CancellablePromise<scribe$0.SelfUpdateResult | null>}
 */
export function UpgradeApp() {
    return $Call.ByID(2917960113).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

// Private type creation functions
const $$createType0 = scribe$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = scribe$0.SourceGroupCheckResult.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = scribe$0.InstallResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = scribe$0.ExistingSkillInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = scribe$0.SkillConflict.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = scribe$0.DiscoverResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = scribe$0.AgentStatus.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = scribe$0.MarketplaceProviderInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = scribe$0.SkillAuditResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = scribe$0.SkillInfo.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = scribe$0.TermsClause.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = scribe$0.WorkspaceInfo.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = scribe$0.MarketplaceResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = scribe$0.UpdateResult.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = scribe$0.SelfUpdateResult.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
