// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentStatus represents an agent's installation status for the frontend
 */
export class AgentStatus {
    /**
     * Creates a new AgentStatus instance.
     * @param {Partial<AgentStatus>} [$$source = {}] - The source object to create the AgentStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("skillCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skillCount"] = 0;
        }
        if (!("globalSkillsDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["globalSkillsDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentStatus(/** @type {Partial<AgentStatus>} */($$parsedSource));
    }
}

/**
 * AuditAlert represents a single alert from a security audit provider
 */
export class AuditAlert {
    /**
     * Creates a new AuditAlert instance.
     * @param {Partial<AuditAlert>} [$$source = {}] - The source object to create the AuditAlert.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["file"] = null;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("confidence" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["confidence"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditAlert instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditAlert}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditAlert(/** @type {Partial<AuditAlert>} */($$parsedSource));
    }
}

/**
 * AuditDetail contains detailed security audit information for a specific provider
 */
export class AuditDetail {
    /**
     * Creates a new AuditDetail instance.
     * @param {Partial<AuditDetail>} [$$source = {}] - The source object to create the AuditDetail.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["result"] = "";
        }
        if (!("riskLevel" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["riskLevel"] = null;
        }
        if (!("analysisHtml" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["analysisHtml"] = null;
        }
        if (!("analyzedAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["analyzedAt"] = null;
        }
        if (!("alerts" in $$source)) {
            /**
             * @member
             * @type {AuditAlert[]}
             */
            this["alerts"] = [];
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditDetail}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("alerts" in $$parsedSource) {
            $$parsedSource["alerts"] = $$createField5_0($$parsedSource["alerts"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField6_0($$parsedSource["metadata"]);
        }
        return new AuditDetail(/** @type {Partial<AuditDetail>} */($$parsedSource));
    }
}

/**
 * DiscoverResult is the frontend-friendly result of discovering skills from a source
 */
export class DiscoverResult {
    /**
     * Creates a new DiscoverResult instance.
     * @param {Partial<DiscoverResult>} [$$source = {}] - The source object to create the DiscoverResult.
     */
    constructor($$source = {}) {
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {DiscoveredSkill[]}
             */
            this["skills"] = [];
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("sourceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoverResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        return new DiscoverResult(/** @type {Partial<DiscoverResult>} */($$parsedSource));
    }
}

/**
 * DiscoveredSkill represents a skill found during source discovery (before install)
 */
export class DiscoveredSkill {
    /**
     * Creates a new DiscoveredSkill instance.
     * @param {Partial<DiscoveredSkill>} [$$source = {}] - The source object to create the DiscoveredSkill.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("alreadyInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alreadyInstalled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredSkill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoveredSkill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveredSkill(/** @type {Partial<DiscoveredSkill>} */($$parsedSource));
    }
}

/**
 * ExistingSkillInfo represents a skill found in an agent's directory during onboarding
 */
export class ExistingSkillInfo {
    /**
     * Creates a new ExistingSkillInfo instance.
     * @param {Partial<ExistingSkillInfo>} [$$source = {}] - The source object to create the ExistingSkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * Full path to the skill directory
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("agentId" in $$source)) {
            /**
             * Which agent it was found in
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (!("agentName" in $$source)) {
            /**
             * Display name of the agent
             * @member
             * @type {string}
             */
            this["agentName"] = "";
        }
        if (!("isGitRepo" in $$source)) {
            /**
             * Whether the skill directory is a git repo
             * @member
             * @type {boolean}
             */
            this["isGitRepo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExistingSkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExistingSkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExistingSkillInfo(/** @type {Partial<ExistingSkillInfo>} */($$parsedSource));
    }
}

/**
 * InstallResult contains the result of a URL scheme installation
 */
export class InstallResult {
    /**
     * Creates a new InstallResult instance.
     * @param {Partial<InstallResult>} [$$source = {}] - The source object to create the InstallResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("skillsCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skillsCount"] = 0;
        }
        if (!("skillNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skillNames"] = [];
        }
        if (!("errorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skillNames" in $$parsedSource) {
            $$parsedSource["skillNames"] = $$createField2_0($$parsedSource["skillNames"]);
        }
        return new InstallResult(/** @type {Partial<InstallResult>} */($$parsedSource));
    }
}

/**
 * MarketplaceProviderInfo is the frontend-friendly representation of a provider
 */
export class MarketplaceProviderInfo {
    /**
     * Creates a new MarketplaceProviderInfo instance.
     * @param {Partial<MarketplaceProviderInfo>} [$$source = {}] - The source object to create the MarketplaceProviderInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketplaceProviderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketplaceProviderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarketplaceProviderInfo(/** @type {Partial<MarketplaceProviderInfo>} */($$parsedSource));
    }
}

/**
 * MarketplaceRepo represents a repository found in the marketplace
 */
export class MarketplaceRepo {
    /**
     * Creates a new MarketplaceRepo instance.
     * @param {Partial<MarketplaceRepo>} [$$source = {}] - The source object to create the MarketplaceRepo.
     */
    constructor($$source = {}) {
        if (!("owner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("fullName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullName"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("avatarUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatarUrl"] = "";
        }
        if (!("stars" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stars"] = 0;
        }
        if (!("skillCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skillCount"] = 0;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["downloads"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["verified"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["category"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketplaceRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketplaceRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarketplaceRepo(/** @type {Partial<MarketplaceRepo>} */($$parsedSource));
    }
}

/**
 * MarketplaceResult holds the search results from a marketplace provider
 */
export class MarketplaceResult {
    /**
     * Creates a new MarketplaceResult instance.
     * @param {Partial<MarketplaceResult>} [$$source = {}] - The source object to create the MarketplaceResult.
     */
    constructor($$source = {}) {
        if (!("repos" in $$source)) {
            /**
             * @member
             * @type {MarketplaceRepo[]}
             */
            this["repos"] = [];
        }
        if (!("totalCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketplaceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketplaceResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repos" in $$parsedSource) {
            $$parsedSource["repos"] = $$createField0_0($$parsedSource["repos"]);
        }
        return new MarketplaceResult(/** @type {Partial<MarketplaceResult>} */($$parsedSource));
    }
}

/**
 * SelfUpdateResult contains the outcome of a self-update attempt.
 */
export class SelfUpdateResult {
    /**
     * Creates a new SelfUpdateResult instance.
     * @param {Partial<SelfUpdateResult>} [$$source = {}] - The source object to create the SelfUpdateResult.
     */
    constructor($$source = {}) {
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updated"] = false;
        }
        if (!("oldVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["oldVersion"] = "";
        }
        if (!("newVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["newVersion"] = "";
        }
        if (!("installMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installMethod"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["components"] = undefined;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelfUpdateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SelfUpdateResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField4_0($$parsedSource["components"]);
        }
        return new SelfUpdateResult(/** @type {Partial<SelfUpdateResult>} */($$parsedSource));
    }
}

/**
 * SkillAudit represents a single security audit result for a marketplace skill
 */
export class SkillAudit {
    /**
     * Creates a new SkillAudit instance.
     * @param {Partial<SkillAudit>} [$$source = {}] - The source object to create the SkillAudit.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * Audit tool provider name (e.g., "vibesafe")
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * Human-readable audit label
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * Result status: "Pass", "Warn", "Fail", etc.
             * @member
             * @type {string}
             */
            this["result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillAudit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillAudit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillAudit(/** @type {Partial<SkillAudit>} */($$parsedSource));
    }
}

/**
 * SkillAuditResult is the response from fetching audits for a skill
 */
export class SkillAuditResult {
    /**
     * Creates a new SkillAuditResult instance.
     * @param {Partial<SkillAuditResult>} [$$source = {}] - The source object to create the SkillAuditResult.
     */
    constructor($$source = {}) {
        if (!("audits" in $$source)) {
            /**
             * @member
             * @type {SkillAudit[]}
             */
            this["audits"] = [];
        }
        if (!("auditDetails" in $$source)) {
            /**
             * @member
             * @type {AuditDetail[]}
             */
            this["auditDetails"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillAuditResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillAuditResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("audits" in $$parsedSource) {
            $$parsedSource["audits"] = $$createField0_0($$parsedSource["audits"]);
        }
        if ("auditDetails" in $$parsedSource) {
            $$parsedSource["auditDetails"] = $$createField1_0($$parsedSource["auditDetails"]);
        }
        return new SkillAuditResult(/** @type {Partial<SkillAuditResult>} */($$parsedSource));
    }
}

/**
 * SkillConflict represents a naming conflict between skills from different agents
 */
export class SkillConflict {
    /**
     * Creates a new SkillConflict instance.
     * @param {Partial<SkillConflict>} [$$source = {}] - The source object to create the SkillConflict.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sources" in $$source)) {
            /**
             * @member
             * @type {ExistingSkillInfo[]}
             */
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillConflict}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField1_0($$parsedSource["sources"]);
        }
        return new SkillConflict(/** @type {Partial<SkillConflict>} */($$parsedSource));
    }
}

/**
 * SkillInfo is the frontend-friendly representation of a skill
 */
export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Storage/directory name (possibly source-qualified)
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Frontmatter name (always simple, e.g. "commit")
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * Human-readable source
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("sourceType" in $$source)) {
            /**
             * github, local, url, etc.
             * @member
             * @type {string}
             */
            this["sourceType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Full URL to source repo/page
             * @member
             * @type {string | undefined}
             */
            this["sourceUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Full SKILL.md file text for local search
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (!("installedAt" in $$source)) {
            /**
             * ISO formatted timestamp
             * @member
             * @type {string}
             */
            this["installedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["contentHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["commitHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["commitDate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * True if source required authentication
             * @member
             * @type {boolean | undefined}
             */
            this["isPrivate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * True for non-removable system skills
             * @member
             * @type {boolean | undefined}
             */
            this["isSystem"] = undefined;
        }
        if (!("agents" in $$source)) {
            /**
             * List of agent IDs with this skill
             * @member
             * @type {string[]}
             */
            this["agents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField14_0($$parsedSource["agents"]);
        }
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

/**
 * SourceGroupCheckResult summarizes an update check for all skills from a single source.
 */
export class SourceGroupCheckResult {
    /**
     * Creates a new SourceGroupCheckResult instance.
     * @param {Partial<SourceGroupCheckResult>} [$$source = {}] - The source object to create the SourceGroupCheckResult.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("hasUpdates" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpdates"] = false;
        }
        if (!("updatedSkillNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["updatedSkillNames"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * New skills in source not yet installed
             * @member
             * @type {DiscoveredSkill[] | undefined}
             */
            this["newAvailableSkills"] = undefined;
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceGroupCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceGroupCheckResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updatedSkillNames" in $$parsedSource) {
            $$parsedSource["updatedSkillNames"] = $$createField2_0($$parsedSource["updatedSkillNames"]);
        }
        if ("newAvailableSkills" in $$parsedSource) {
            $$parsedSource["newAvailableSkills"] = $$createField3_0($$parsedSource["newAvailableSkills"]);
        }
        return new SourceGroupCheckResult(/** @type {Partial<SourceGroupCheckResult>} */($$parsedSource));
    }
}

/**
 * TermsClause is a single clause in the terms and conditions.
 */
export class TermsClause {
    /**
     * Creates a new TermsClause instance.
     * @param {Partial<TermsClause>} [$$source = {}] - The source object to create the TermsClause.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TermsClause instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TermsClause}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TermsClause(/** @type {Partial<TermsClause>} */($$parsedSource));
    }
}

/**
 * UpdateInfo contains information about an available application update
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (!("releaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseURL"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * UpdateResult contains the outcome of a skill update operation
 */
export class UpdateResult {
    /**
     * Creates a new UpdateResult instance.
     * @param {Partial<UpdateResult>} [$$source = {}] - The source object to create the UpdateResult.
     */
    constructor($$source = {}) {
        if (!("skillName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skillName"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * True if skill was removed (no longer in source)
             * @member
             * @type {boolean | undefined}
             */
            this["removed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Previous commit hash or truncated content hash
             * @member
             * @type {string | undefined}
             */
            this["oldHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * New commit hash or truncated content hash
             * @member
             * @type {string | undefined}
             */
            this["newHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * New commit date if available
             * @member
             * @type {string | undefined}
             */
            this["commitDate"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateResult(/** @type {Partial<UpdateResult>} */($$parsedSource));
    }
}

/**
 * WorkspaceInfo is the frontend-friendly representation of a workspace
 */
export class WorkspaceInfo {
    /**
     * Creates a new WorkspaceInfo instance.
     * @param {Partial<WorkspaceInfo>} [$$source = {}] - The source object to create the WorkspaceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("skills" in $$source)) {
            /**
             * Skill names in this workspace
             * @member
             * @type {string[]}
             */
            this["skills"] = [];
        }
        if (!("isActive" in $$source)) {
            /**
             * Whether this is the active workspace
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        return new WorkspaceInfo(/** @type {Partial<WorkspaceInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AuditAlert.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = DiscoveredSkill.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = MarketplaceRepo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = SkillAudit.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = AuditDetail.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ExistingSkillInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
